export const CHANGE_MAIN_COLORS = "CHANGE_MAIN_COLORS";
export const CHANGE_MAIN_BUTTON = "CHANGE_MAIN_BUTTON";
export const CHANGE_SECONDARY_BUTTON = "CHANGE_SECONDARY_BUTTON";
export const CHANGE_TERTIARY_BUTTON = "CHANGE_TERTIARY_BUTTON";
export const CHANGE_INPUT = "CHANGE_INPUT";
export const CHANGE_ARTICLE_BACKGROUND = "CHANGE_ARTICLE_BACKGROUND";
export const CHANGE_GENERIC_BOX_BACKGROUND = "CHANGE_GENERIC_BOX_BACKGROUND";
export const CHANGE_LINK_COLOR = "CHANGE_LINK_COLOR";
